<!DOCTYPE html>
<html lang="en">
<!--*******************************************__ Forget password View __*************************************-->

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="<?=asset('assets/css/Favicon_GC.png');?>">
  <title>Gestion des conges</title>
  <!------------------------ Tell the browser to be responsive to screen width ------------------------->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!------------------------------------------ Bootstrap 3.3.7 ----------------------------------------->
  <link rel="stylesheet" href="<?=asset('assets/css/bower_components/bootstrap/dist/css/bootstrap.min.css');?>">
  <!------------------------------------------- Font Awesome ------------------------------------------->
  <link rel="stylesheet" href="<?=asset('assets/css/bower_components/font-awesome/css/font-awesome.min.css');?>">
  <!--------------------------------------------- Ionicons --------------------------------------------->
  <link rel="stylesheet" href="<?=asset('assets/css/bower_components/Ionicons/css/ionicons.min.css');?>">
  <!------------------------------------------- Theme style -------------------------------------------->
  <link rel="stylesheet" href="<?=asset('dist/css/AdminLTE.min.css');?>">
  <link rel="stylesheet" href="<?=asset('assets/css/mystyle.css');?>"> 
  <!------------------------------------------- Google Font -------------------------------------------->
  <link rel="stylesheet" 
  href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>


<body class="body">
  <br/><br/><br/><br/><br/><br/> <br/>
<div class="login-box">
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Veuillez indiquer votre adresse email</p>

    <form action="" method="post">
      <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="Email" name="email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <center><input type="submit" class="red-log-sub" value="Valider" /></center><br/>
      <a href="<?=constructUrl('login'); ?>" id="mauve">J'ai déjà un Compte</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a href="<?=constructUrl('register'); ?>" class="text-center" id="vert">Créer un compte</a><br/><br/>
    </form>
  </div>
</div>
</body>
</html>
