<!DOCTYPE html>
<html lang="en">
<!-- *******************************************__ Header View __************************************* -->

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <meta name="description" content="with draggable and editable events" />
  <link rel="icon" type="image/x-icon" href="<?=asset('assets/css/Favicon_GC.png');?>">
  <title>Gestion des conges</title>

  <link rel="stylesheet" href="<?=asset('assets/css/select2.min.css');?>" />
  <!------------------------------------------------ bootstrap & fontawesome ----------------------------------->
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/css/bootstrap.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/font-awesome/4.5.0/css/font-awesome.min.css');?>" />
  <!------------------------------------------------ page specific plugin styles ------------------------------->
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/css/jquery-ui.custom.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/css/fullcalendar.min.css');?>" />
  <!------------------------------------------------ text fonts ------------------------------------------------>
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/css/fonts.googleapis.com.css');?>" />
  <!------------------------------------------------ Google Font ----------------------------------------------->
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/css/fonts.googleapis.com.css');?>" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  <!------------------------------------------------ ace styles ------------------------------------------------>
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/css/ace.min.css');?>" class="ace-main-stylesheet" id="main-ace-style" />
  <link rel="stylesheet" href="<?=asset('assets/css/dropzone.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/css/ace-skins.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets\ace-style\assets/css/ace-rtl.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/chosen.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/bootstrap-datepicker3.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/bootstrap-timepicker.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/daterangepicker.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/bootstrap-datetimepicker.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/bootstrap-colorpicker.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/ace-skins.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/ace-rtl.min.css');?>" />
  <link rel="stylesheet" href="<?=asset('assets/css/bower_components/select2/dist/css/select2.min.css');?>">
  <link rel="stylesheet" href="<?=asset('assets/css/mystyle.css');?>">
  <!-- inline styles related to this page -->
  <!----------------------------- ace settings handler ----------------------------->
  <script src="<?=asset('assets/js/ace-extra.min.j');?>s"></script>
  <!----------------------------- ace settings handler ----------------------------->
  <script src="<?=asset('assets\ace-style\assets/js/ace-extra.min.js');?>"></script>
  <script src="<?=asset('assets\ace-style\assets/js/jquery-2.1.4.min.js');?>"></script>
  <script src="<?=asset('assets/js/jquery.validate.min.js');?>"></script>
</head>

<body class="no-skin">
  <div id="navbar" class="navbar navbar-default ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
    <img src="<?=asset('assets/css/Logo_GC.png');?>"  alt="Logo Image"
                style="width: 108px; height: 44px;">

      <div class="navbar-buttons navbar-header pull-right" role="navigation" style="width:200px;">
        <ul class="nav ace-nav" style="width:200px;">

          <li class="light-blue dropdown-modal" style="width:200px;">
            <a data-toggle="dropdown" href="#" class="dropdown-toggle" style="width:200px;">
              <img src="<?=asset('assets/css/user1.png');?>" class="img-circle" alt="User Image"
                style="width: 36px; height: 36px;">
              <span class="user-info" style="width:300px;">
                <?= $_SESSION['nom'];?>
              </span>

              <i class="ace-icon fa fa-caret-down"></i>
            </a>
            <ul class="user-menu dropdown-menu-right dropdown-menu  dropdown-close" style="width:200px;margin-top: 3px;margin-right: 4px;">
            <li style="width:200px;">
                <a href="#" data-toggle="modal" data-target="#myModal1">
                  <i class="ace-icon fa fa-cogs"></i>
                  Paramètres de compte
                </a>
              </li>
              <li style="width:200px;">
                <a href="<?=constructUrl('logout');?>">
                  <i class="ace-icon fa fa-power-off"></i>
                  Log out
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div><!-- /.navbar-container -->
  </div>
  <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="background-color: #438EB9; color:#FFFFFF;">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Paramètres de compte</h4>
        </div>
        <!-- ---------Form Paramétre de compte----------- -->
        <form  id="update_form">
          <div class="modal-body">
          <div class="alert alert-success" id="success1">
              <!-- <button type="button" class="close" data-dismiss="alert">
                <i class="ace-icon fa fa-times"></i>
              </button> -->
              <strong>
                <i class="ace-icon fa fa-check"></i>
                Bien Fait!
              </strong>
              les informations ont été bien modifier.
              <br />
            </div>
            <div class="form-group">
            <div>
              <input type="hidden" name="iduser" id="iduser" value="<?= $_SESSION['id_user'];?>">
            </div>  
            <div>
              <label for="nom">Nom Complet :</label>
              <input type="text" class="form-control ng-pristine ng-untouched ng-valid ng-valid-maxlength" id="flname"
                maxlength="40" ng-disabled="true" name="flname" value="<?= $_SESSION['nom'];?>">
            </div>  
            <div>
              <label for="Sexe">Sexe :</label>
              <select class="form-control ng-pristine ng-untouched ng-valid" id="seexe" name="seexe">
              <?php if ($_SESSION['sexe'] =='Mr'): ?>
                  <option value="Mr" selected="selected">Mr</option>
                  <option value="Mrs">Mrs</option>
              <?php else: ?>
                  <option value="Mr">Mr</option>
                  <option value="Mrs" selected="selected">Mrs</option>
              <?php endif; ?>
              </select>
            </div>
            <div>
              <label for="gsm">Gsm :</label>
              <input type="text" class="form-control ng-pristine ng-untouched ng-valid ng-valid-maxlength" name="phone"
                id="phone" maxlength="20" ng-disabled="true" value="<?= $_SESSION['gsm'];?>">
            </div>
            <div>
              <label for="email">Email :</label>
              <input type="email" class="form-control ng-pristine ng-untouched ng-valid ng-valid-maxlength" name="mail"
                id="mail" maxlength="20" ng-disabled="true" value="<?= $_SESSION['email'];?>" disabled>
            </div>
            <div>
              <label for="pwd">Mot de passe :</label>
              <input type="password" class="form-control ng-pristine ng-untouched ng-valid ng-valid-maxlength"
                name="motDePasse" id="motDePasse" maxlength="20" ng-disabled="true" value="<?= $_SESSION['M_Passe'];?>">
            </div>
            <div>
              <label for="cpwd">Confirmer votre mot de passe :</label>
              <input type="password" class="form-control ng-pristine ng-untouched ng-valid ng-valid-maxlength"
                name="motDePasse1" id="motDePasse1" maxlength="20" ng-disabled="true" value="<?= $_SESSION['M_Passe'];?>">
            </div>
          </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-sm btn-success" id="mprofil"> Valider<i class="ace-icon fa fa-check"></i></button>
            </br>
            </br>
          </div>
      </div>
      </form>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  
<div id="main-container" class="main-container responsive ace-save-state" >
  <script>
    try { ace.settings.loadState('main-container') } catch (e) { }
  </script>
  
  <div id="sidebar" class="sidebar responsive ace-save-state">
  <script>
    try { ace.settings.loadState('sidebar') } catch (e) { }
  </script>
  <!-- </div> -->
  <!-- </div> -->

<script>
$(document).ready(function() {
  $('#success1').hide();
    $('#update_form').validate({
              
        errorElement: 'div',
        errorClass: 'help-block',
        focusInvalid: false,
        ignore: "",
        rules: {
            flname: {required: true},
            phone: {required: true},
            motDePasse: {required: true, minlength: 8},
            // motDePasse1: {required: true, equalTo: "#motDePasse"},
        },

        messages: {
            flname: {required: "Veuillez saisir un nom"},
            phone: {required: "Veuillez saisir un numéro de téléphone"},
            motDePasse: {
                required: "Veuillez entrer un mot de passe",
                minlength: "Veuillez spécifier un mot de passe qui dépasse 8 caractères"
            }
            // motDePasse1: {
            //   required: "Veuillez entrer votre mot de passe",
            //   minlength: "Veuillez spécifier un mot de passe qui dépasse 5 caractères",
            //   equalTo: "Les deux mots de passes doivent êtres identiques"
            // }
        },

        highlight: function (e) {
            $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
        },

        success: function (e) {
            $(e).closest('.form-group').removeClass('has-error');
            $(e).remove();
        },

        errorPlacement: function (error, element) {
            if (element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
                var controls = element.closest('div[class*="col-"]');
                if (controls.find(':checkbox,:radio').length > 1) controls.append(error);
                else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
            }

            else if (element.is('.select2')) {
                error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
            }

            else if (element.is('.chosen-select')) {
                error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
            }

            else error.insertAfter(element.parent());
        },

        submitHandler: function (form) 
        {
            const idUser = $("#iduser").val();
            const flname = $("#flname").val();
            const seexe = $("#seexe").val();
            const phone = $("#phone").val();
            const mail = $("#mail").val();
            const motDePasse = $("#motDePasse").val();
            console.log('ok submit');
           
            $.ajax({
                url: '<?=constructUrl('UpdateSettings');?>',
                type: 'POST',
                data: {
                    iduser: idUser, 
                    flname: flname,
                    seexe: seexe,
                    phone: phone, 
                    mail: mail, 
                    motDePasse: motDePasse
                },
                dataType: 'json',
                success: function(json) {
                  $(".user-info").text(json[1]);
                  $("#iduser").val(json[0]);
                  $("#flname").val(json[1]);
                  $("#seexe").val(json[2]);
                  $("#phone").val(json[3]);
                  $("#motDePasse").val(json[4]);
                  $("#motDePasse1").val(json[4]);
                      $('#success1').show();
                      setTimeout(function() {
                          $('#success1').hide();
                      }, 3000);
                  }
            })
        }
      }
    )
    });


</script>


  